<?xml version="1.0" encoding="utf-8"?><Database Name="mechani1MeTest" Class="MechanicalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=31.25.89.145,2012;Initial Catalog=mechani1MeTest;Persist Security Info=True;User ID=mechani1sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MeTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACL" Member="ACLs">
    <Type Name="ACL">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdvisorType" Member="AdvisorTypes">
    <Type Name="AdvisorType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaperId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CommentInFroum" Member="CommentInFroums">
    <Type Name="CommentInFroum">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Desk" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FroumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumofLike" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NumofDisLike" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CommentInObject" Member="CommentInObjects">
    <Type Name="CommentInObject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Desk" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CommentInPaper" Member="CommentInPapers">
    <Type Name="CommentInPaper">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Desk" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PaperId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Executertype" Member="Executertypes">
    <Type Name="Executertype">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Favorite" Member="Favorites">
    <Type Name="Favorite">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Froum" Member="Froums">
    <Type Name="Froum">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Froum" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Like]" Member="Likes">
    <Type Name="Like">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaperId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Seen" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LikeInFroum" Member="LikeInFroums">
    <Type Name="LikeInFroum">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FroumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LikeInObject" Member="LikeInObjects">
    <Type Name="LikeInObject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LikeInPaper" Member="LikeInPapers">
    <Type Name="LikeInPaper">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaperId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.List" Member="Lists">
    <Type Name="List">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ListItem" Member="ListItems">
    <Type Name="ListItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ListId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[main.Object]" Member="main_Objects">
    <Type Name="main_Object">
      <Column Name="userId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cellphone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ObjectTypeId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ObjectBrandTypeId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instagram" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LinkedIn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Google" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Site" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Twitter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Long" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Seen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Submit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="serverDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MainObjectId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mainObject2" Member="mainObject2s">
    <Type Name="mainObject2">
      <Column Name="userId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cellphone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pdf4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ObjectTypeId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ObjectBrandTypeId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instagram" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LinkedIn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Google" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Site" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Twitter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Long" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Seen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Submit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="serverDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MainObjectId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsPaper" Member="NewsPapers">
    <Type Name="NewsPaper">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Object" Member="Objects">
    <Type Name="Object">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image1" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Image2" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Image3" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Image4" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Cellphone" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Pdf1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Pdf2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Pdf3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Pdf4" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ObjectTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectBrandTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Instagram" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LinkedIn" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Google" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Site" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Twitter" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MainObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image1Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image2Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image3Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="AgencyService" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmitDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Object" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectBrandType" Member="ObjectBrandTypes">
    <Type Name="ObjectBrandType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectInCity" Member="ObjectInCities">
    <Type Name="ObjectInCity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectInProvince" Member="ObjectInProvinces">
    <Type Name="ObjectInProvince">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectType" Member="ObjectTypes">
    <Type Name="ObjectType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paper" Member="Papers">
    <Type Name="Paper">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Context" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Paper" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Papers" Member="Paper1s">
    <Type Name="Paper1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Context" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaperType" Member="PaperTypes">
    <Type Name="PaperType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Province" Member="Provinces">
    <Type Name="Province">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Fav" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report" Member="Reports">
    <Type Name="Report">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Desc]" Member="Desc" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserIdSender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserIdReporter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubAdmin" Member="SubAdmins">
    <Type Name="SubAdmin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="serverDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TicketType" Member="TicketTypes">
    <Type Name="TicketType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Desc]" Member="Desc" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WorkmanType" Member="WorkmanTypes">
    <Type Name="WorkmanType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="mechani1sa.UserProfile" Member="UserProfile1s">
    <Type Name="UserProfile1">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(56) NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile1_webpages_UsersInRole" Member="webpages_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="webpages_UsersInRole" />
    </Type>
  </Table>
  <Table Name="mechani1sa.webpages_Membership" Member="webpages_Memberships">
    <Type Name="webpages_Membership">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPasswordFailureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordFailuresSinceLastSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordVerificationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PasswordVerificationTokenExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="mechani1sa.webpages_OAuthMembership" Member="webpages_OAuthMemberships">
    <Type Name="webpages_OAuthMembership">
      <Column Name="Provider" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderUserId" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="mechani1sa.webpages_Roles" Member="webpages_Roles">
    <Type Name="webpages_Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_UsersInRole" />
    </Type>
  </Table>
  <Table Name="mechani1sa.webpages_UsersInRoles" Member="webpages_UsersInRoles">
    <Type Name="webpages_UsersInRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_Role" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_Role" IsForeignKey="true" />
      <Association Name="UserProfile1_webpages_UsersInRole" Member="UserProfile1" ThisKey="UserId" OtherKey="UserId" Type="UserProfile1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Desc]" Member="Desc" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.Byte[]" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UEmail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UPhonnumber" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UFax" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UAdress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UImage" Type="System.Byte[]" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UMobile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmitDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageServerDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Ticket" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LikeInCommentObject" Member="LikeInCommentObjects">
    <Type Name="LikeInCommentObject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLike" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LikeInComment" Member="LikeInComments">
    <Type Name="LikeInComment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLike" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Phonenumber" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobailenumber" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Faxnumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageServerDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShowInfoItem" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BirthDay" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Froum" Member="Froums" ThisKey="Id" OtherKey="UserId" Type="Froum" />
      <Association Name="User_Object" Member="Objects" ThisKey="Id" OtherKey="UserId" Type="Object" />
      <Association Name="User_Paper" Member="Papers" ThisKey="Id" OtherKey="UserId" Type="Paper" />
      <Association Name="User_Ticket" Member="Tickets" ThisKey="Id" OtherKey="UserId" Type="Ticket" />
    </Type>
  </Table>
  <Table Name="mechani1sa.Visit" Member="Visits">
    <Type Name="Visit">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Anad" Member="Anads">
    <Type Name="Anad">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Admit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmitDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageServerDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CommentInPost" Member="CommentInPosts">
    <Type Name="CommentInPost">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LikeInPost" Member="LikeInPosts">
    <Type Name="LikeInPost">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="mechani1sa.LikeInCommentPost" Member="LikeInCommentPosts">
    <Type Name="LikeInCommentPost">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLike" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="mechani1sa.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Seen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Submit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seenBefore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageServerDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>